### PR TITLE
Added function arithmetic

### PR DESCRIPTION
**Pull request by jakobsandberg**
Added capability to add and multiply functions (of one variable) to make new functions.

For example:

h(x) = f(x) + g(x)

and

h(x) = f(x) * g(x)

Note: these methods return functions themselves. This will allow for many more techniques to be constructed, such as Lagrange Interpolation, which depend on function addition and multiple to return functions themselves and not just evaluations of functions at a single point.

### CODE REVIEW

**Comment by markrogoyski** [comment]
Hi Jakob. Thanks for the pull request.

I'm hesitant to use any code with ```eval``` in it.

Looking at what you are doing, for example in ```add```, perhaps you can replace this:
```php
        eval('$result = function($x) use (' . $expression . ', $sum) {
            return $sum($x, ' . $expression . ');
        };');
```

with something like this:
```php
        $result = function ($x) use ($sum, $args) {
            return call_user_func_array($sum, array_merge([$x], $args));
        };
```

Try something like that and see if you can get it to work. Using ```eval``` should be a last resort.

**Comment by jakobsandberg** [comment]
Mark,

Thanks for the tip! Your method worked perfectly. I'm putting in a new PR right now.

I didn't know you can pass an array to the `use` function, so I thought the only way to do this (for an arbitrary number of variables in `use()`) was via a callback function.

**Comment by jakobsandberg** [comment]
Just made the new commits. Let me know if everything else looks okay.

**Comment by markrogoyski** [comment]
Thanks for updating. I've future simplified it by removing some unnecessary code, and adding callable type hinting to the ...splat parameter so manual validation is not necessary.

I've merged into the develop branch. I'll merge into master when I do the next release (v0.3.0).

Thanks.

**Comment by markrogoyski** [comment]
Thanks for the pull request. Merged and released in v0.3.0.

**Pull request merged**
