### PR TITLE
Made NumericalIntegration classes compatible with callback function inputs

### PR DESCRIPTION
**Pull request by jakobsandberg**
Reflected changes in comments, child classes, tests, and readme examples.

### CODE REVIEW

**Comment by markrogoyski** [comment]
Can you add a unit test for this exception
https://coveralls.io/builds/7675380/source?filename=src%2FNumericalAnalysis%2FNumericalIntegration%2FNumericalIntegration.php#L114

Thanks.

**Comment by markrogoyski** [comment]
How would you feel about using the ...splat operator instead of requiring the user to put the optional callback and bounds parameters in them in an array. That way the user would just add the additional parameters when using that method. It would require minimal changes, since you are already expecting an array as input.
http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list

**Comment by jakobsandberg** [comment]
Yeah I can add the unit test!

Also, the ...splat operator sounds like a good direction to take. So would a callback example look like this?

```
TrapezoidalRule::approximate($func, $a, $b, $c)
```

Essentially dropping the args array, allowing approximate() to have a variable number of arguments.

**Comment by markrogoyski** [comment]
Exactly. It allows variable arguments. And from your function's point of view, it would get them all in an ordered array, which is what you are already expecting.

**Pull request merged**
