### PR TITLE
Weighted correlation

### PR DESCRIPTION
**Pull request by balping**
* Weighted average
* Weighted sample variance
* Weighted covariance
* Weighted correlation

### CODE REVIEW

**Comment by markrogoyski** [comment]
Hi @balping,
Thank you for the pull request. These are good methods to have. Thank you for implementing them.

Thank you for adding unit tests and following the established coding standards. I have merged your changing into _develop_ manually. They are currently in the develop branch and will be included in the next release.

FYI, next time, please point your pull request to the _develop_ branch instead of the _master_ branch.

Thanks again for your pull request. Good stuff.
Mark

**Comment by markrogoyski** [comment]
The new features from your pull request will be released with the next version: v0.42.0.

**Comment by balping** [comment]
OK. Thanks. Just for reference https://github.com/markrogoyski/math-php/commit/1f5162d23296b3039200ec1356f31569d4a610ea

**Comment by markrogoyski** [comment]
These features have been released in [v0.42.0](https://github.com/markrogoyski/math-php/releases/tag/v0.42.0). Thanks again!

**Pull request closed without merging**
