### PR TITLE
Distributions: continuous interface

### PR DESCRIPTION
**Pull request by balping**
https://github.com/markrogoyski/math-php/issues/247

* Added a continuous interface
* unified cdf and pdf signatures to have float type
* removed some unnecessary docblock lines

Please verify that it makes sense to say that the dirac delta distribution has a mean of 0.
https://github.com/balping/math-php/blob/2bbb17dd8f19cd0f38641696efa479103f16a8b5/src/Probability/Distribution/Continuous/DiracDelta.php#L98

### CODE REVIEW

**Comment by Beakerboy** [comment]
I have not done the math, but my initial guess is the mean is undefined.

**Comment by markrogoyski** [comment]
Hi,
Thank you for the pull request!

What is the advantage of the Continuous interface? Every continuous distribution extends MathPHP\Probability\Distribution\Continuous so you could use a type declaration of Distribution\Continuous already. Also, since not every distribution has or implements a mean, not every continuous distribution can implement the Continuous interface.

For the dirac delta distribution mean, if you have a definitive source that defines the mean, please put that in the documentation. And add unit tests.

Thanks.

**Comment by Beakerboy** [comment]
After more thought...maybe the mean is 0. If you take random draws from the distribution, their average will always be 0. I think proving it through integration is tricky (if even possible)

**Comment by balping** [comment]
The inverse function defined in the abstract class, depends on cdf, pdf and mean function. The interface enforces that they are defined, so calling inverse (and rand) doesn't lead to unexpected function not defined errors. The interface also enforces consistency in api across distributions.

I asked a question about the mean of Dirac delta on [math stackoverflow](https://math.stackexchange.com/questions/2470914/does-the-dirac-delta-distribution-have-a-mean/2470921#2470921).  It seems that the mean is indeed 0, so I'll add a test to get that 100% coverage back.

**Comment by markrogoyski** [comment]
Let's note use the word ```Interface``` in the interface and use something more descriptive. Since the interface doesn't describe all Continuous distributions, would it make more sense to call it ```InvertibleDistribution``` or something like that?

**Comment by balping** [comment]
Up until now, it does describe all continuous distributions.

I don't like the `Interface` suffix either, normally I would have gone for `Continuous`, but that's already taken

**Comment by markrogoyski** [comment]
Thanks for the pull request. I renamed the interface ```ContinuousDistribution```.

**Pull request merged**
