### PR TITLE
Added null mean when v <= 1

### PR DESCRIPTION
**Pull request by Beakerboy**

### CODE REVIEW

**Comment by markrogoyski** [comment]
What is your opinion of using \NAN instead of null when the value is undefined.

For example, the built-in math functions have that behavior:
```php
sqrt(-1);
acos(2);
```
Those will return \NAN.

I tend to think that null just means a value hasn't been set. A variable exists, but it hasn't been set to anything yet.

Whereas NAN is the result of some mathematical operation that does not make sense.
Thoughts?

**Comment by Beakerboy** [comment]
That sounds good.

**Comment by markrogoyski** [comment]
Did you intend to close this pull request before I had pulled and merged it?

**Comment by Beakerboy** [comment]
I closed because it had some issues. If I have time Sunday morning I plan on getting everything closed up as well as I can.

**Comment by markrogoyski** [comment]
Oh OK. No worries. Just curious. No need to rush. Thanks for the continued contributions!

**Pull request closed without merging**
