### PR TITLE
Karatsuba algorithm for ArbitraryInteger::multiply()

### PR DESCRIPTION
**Pull request by Beakerboy**
An implementation of a more efficient multiplication algorithm. I have not done any performance measurement to see if it actually IS faster. I thought you’d have ideas on the best way to do that.

### CODE REVIEW

**Comment by markrogoyski** [comment]
There was no previous unit test for direct calls to multiply? I guess `pow`, `fact` and `BaseEncoderDecoder` wouldn't work if multiply was broken. How did I miss that? =)

I'll run some tests and report back on the performance results.

**Comment by Beakerboy** [comment]
Yeah, I was surprised I missed that. All the functions that call `multiply()` in tests must call with a positive integer. The Katasuba pull request contains all the changes in the bug fix...but it might be good just to pull the fix first in case the performance measurement doesn’t look good, or more important things come up.

**Comment by markrogoyski** [comment]
Here are my unscientific performance test results. I ran various unit tests multiple times.

**Multiply**
```
$ git checkout develop
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testMultiplication --repeat=1000

Time: 12.38 seconds, Memory: 6.00 MB
Time: 16.23 seconds, Memory: 6.00 MB
Time: 11.84 seconds, Memory: 6.00 MB
Time: 15.01 seconds, Memory: 6.00 MB

$ git checkout Beakerboy-Karatsuba
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testFact --repeat=20

Time: 16.22 seconds, Memory: 6.00 MB
Time: 20.07 seconds, Memory: 6.00 MB
Time: 17.98 seconds, Memory: 6.00 MB
Time: 16.59 seconds, Memory: 6.00 MB
```

**Factorial**
```
$ git checkout develop
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testFact --repeat=20

Time: 32.77 seconds, Memory: 6.00 MB
Time: 32.58 seconds, Memory: 6.00 MB
Time: 32.56 seconds, Memory: 6.00 MB

$ git checkout Beakerboy-Karatsuba
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testFact --repeat=20

Time: 35.7 seconds, Memory: 6.00 MB
Time: 35.7 seconds, Memory: 6.00 MB
Time: 35.81 seconds, Memory: 6.00 MB
```

**Pow**
```
$ git checkout develop
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testPow --repeat=1000

Time: 19.07 seconds, Memory: 6.00 MB
Time: 22.92 seconds, Memory: 6.00 MB
Time: 18.96 seconds, Memory: 6.00 MB

git checkout Beakerboy-Karatsuba
../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testPow --repeat=1000

Time: 22.89 seconds, Memory: 6.00 MB
Time: 20.02 seconds, Memory: 6.00 MB
Time: 26.05 seconds, Memory: 6.00 MB
```

Seems like it is slightly slower. I did these test on an old i5 Macbook Pro. I can try on a newer processor and see if I get the same results.

**Comment by Beakerboy** [comment]
The full test suite ran slightly slower, so I was worried this would be the case. If you have any thoughts on where some time can be shaved off, let me know. I wonder if the additional object construction from the recursion adds more time than the reduction in multiplication.

**Comment by Beakerboy** [comment]
The commented-out Ackerman Test would be a good one too.

MathPHP\Tests\Functions\ArbitraryIntegerTest::testAckermann()

**Comment by markrogoyski** [comment]
**Ackerman**

```
$ git checkout develop
$ ../vendor/bin/phpunit Functions/ArbitraryIntegerTest.php --filter=testAckermann --repeat=5

Time: 1.12 minutes, Memory: 4.00 MB
Time: 1.12 minutes, Memory: 4.00 MB
Time: 1.12 minutes, Memory: 4.00 MB

$ git checkout Beakerboy-Karatsuba
$ ../vendor/bin/phpunit Functions/ArbitraryIntegerTest.php --filter=testAckermann --repeat=5

Time: 1.13 minutes, Memory: 4.00 MB
Time: 1.12 minutes, Memory: 4.00 MB
Time: 1.13 minutes, Memory: 4.00 MB
```

**Comment by markrogoyski** [comment]
Results from a much faster computer.

**All ArbitraryInteger Tests**
```
$ git checkout develop
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --repeat=100

Time: 1.87 minutes, Memory: 6.00 MB
Time: 1.87 minutes, Memory: 6.00 MB

$ git checkout Beakerboy-Karatsuba
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --repeat=100

Time: 2.05 minutes, Memory: 6.00 MB
Time: 2.07 minutes, Memory: 6.00 MB
```

**Multiply**
```
$ git checkout develop
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testMultiplication --repeat=1000

Time: 5.43 seconds, Memory: 6.00 MB
Time: 5.46 seconds, Memory: 6.00 MB

$ git checkout Beakerboy-Karatsuba
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testMultiplication --repeat=1000

Time: 5.62 seconds, Memory: 6.00 MB
Time: 5.69 seconds, Memory: 6.00 MB
```

**Factorial**
```
$ git checkout develop
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testFact --repeat=20

Time: 21.52 seconds, Memory: 6.00 MB

$ git checkout Beakerboy-Karatsuba
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testFact --repeat=20

Time: 23.84 seconds, Memory: 6.00 MB
```

**Ackermann**
```
$ git checkout develop
$ ../vendor/bin/phpunit Functions/ArbitraryIntegerTest.php --filter=testAckermann --repeat=5

Time: 45.35 seconds, Memory: 4.00 MB
Time: 45.33 seconds, Memory: 4.00 MB

$ git checkout Beakerboy-Karatsuba
$ ../vendor/bin/phpunit Functions/ArbitraryIntegerTest.php --filter=testAckermann --repeat=5

Time: 45.23 seconds, Memory: 4.00 MB
Time: 45.39 seconds, Memory: 4.00 MB
```

**Comment by Beakerboy** [comment]
I reviewed the Ackerman function, and it uses left shifts and addition and subtraction, so it's not surprising that these code changes had little effect on that test. Factorial and Power are probably best.

**Comment by markrogoyski** [comment]
I did some more performance tests with the updated code compared to the code in develop. Pow for some reason had a lot of variance this time. Could just be my poor computer heating up with the fan blowing. Anyways, it seems like they are about the same speed now for factorial. Pow it is hard to say as it was not very consistent.

**Factorial**
```
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testFact --repeat=20

Time: 29.99 seconds, Memory: 6.00 MB
Time: 29.73 seconds, Memory: 6.00 MB

$ git checkout Beakerboy-Karatsuba
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testFact --repeat=20

Time: 29.73 seconds, Memory: 6.00 MB
Time: 29.32 seconds, Memory: 6.00 MB
```

**Pow**
```
$ git checkout develop
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testPow --repeat=1000

Time: 19.18 seconds, Memory: 6.00 MB
Time: 17.14 seconds, Memory: 6.00 MB
Time: 20 seconds, Memory: 6.00 MB
Time: 16.31 seconds, Memory: 6.00 MB
Time: 17.28 seconds, Memory: 6.00 MB

$ git checkout Beakerboy-Karatsuba
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testPow --repeat=1000

Time: 17.16 seconds, Memory: 6.00 MB
Time: 17.8 seconds, Memory: 6.00 MB
Time: 17.77 seconds, Memory: 6.00 MB
Time: 18.81 seconds, Memory: 6.00 MB
Time: 19.72 seconds, Memory: 6.00 MB
```

**Pow with even more repetitions**
```
$ git checkout develop
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testPow --repeat=10000

Time: 3.09 minutes, Memory: 8.00 MB
Time: 2.62 minutes, Memory: 8.00 MB

$ git checkout Beakerboy-Karatsuba
$ ../vendor/bin/phpunit Number/ArbitraryIntegerTest.php --filter=testPow --repeat=10000

Time: 3.88 minutes, Memory: 8.00 MB
Time: 2.96 minutes, Memory: 8.00 MB
```

**Comment by Beakerboy** [comment]
This was an interesting idea, but performance was not improved.

**Pull request closed without merging**
