### PR TITLE
Permutation precision error

### PR DESCRIPTION
**Pull request by Beakerboy**
Preventing the factorial from overflowing.

### CODE REVIEW

**Comment by markrogoyski** [comment]
Thanks for following up and improving permutations as well.

**Comment by Beakerboy** [comment]
I wrote a simple for loop to test all $n less than 100 and all $k < $n to find the first permutation where (float) (int) $perm !== $perm as long as $perm < PHP_INT_MAX. The new test case failed.

**Comment by markrogoyski** [comment]
What were you expecting to happen? And did the previous code fair any better?

**Comment by Beakerboy** [comment]
I’m saying, I expected the old code to have an issue, and this is how I found the test case that would fail.

**Comment by markrogoyski** [comment]
OK I got it. Old code fails in test case `[23,  5, 4037880],` and passes now. Thanks.

For reference:
```
Failed asserting that 4037880.0000000005 matches expected 4037880.0.
```

**Pull request merged**
