### PR TITLE
SetTheory: n-ary Cartesian Product

### PR DESCRIPTION
**Pull request by Theriault**
Add ability to do n-ary Cartesian products

### CODE REVIEW

**Comment by Beakerboy** [comment]
Would we want this to support objects that implement ObjectArithmatic?

**Comment by markrogoyski** [comment]
Hi @Theriault,

Thanks for the pull request to add n-ary cartesian products. Please add some unit tests for cartesian products of three or more sets.

Thanks again.

**Comment by Theriault** [comment]
Hey @markrogoyski - I added some tests for sets of 3. Let me know if that's enough or if more is needed. thanks!

**Comment by markrogoyski** [comment]
Looks good. Sorry for the delay in reviewing.

Just one thing. Resubmit the pull request to merge into develop, rather than master. All PRs and commits go into develop and then develop is merged once into master to cut a release.

Thanks!

**Pull request closed without merging**
