### PR TITLE
QR with Householder Reflections

### PR DESCRIPTION
**Pull request by Beakerboy**
Now works on tall matricies

### CODE REVIEW

**Comment by markrogoyski** [comment]
Thanks for the pull request. I apologize if there was any confusion about what was merged or what.

I was adding more unit tests, and I found a case where it does a division by zero and crashes.

```php
            [
                [
                    [0],
                    [0],
                ],
                [
                    'Q' => [
                        [1],
                        [0],
                    ],
                    'R' => [
                        [0],
                    ],
                ],
            ],
```

```
There was 1 error:

1) MathPHP\Tests\LinearAlgebra\MatrixDecompositionsTest::testQrDecomposition1 with data set #8 (array(array(0), array(0)), array(array(array(1), array(0)), array(array(0))))
Division by zero

/src/LinearAlgebra/Matrix.php:3522
/src/LinearAlgebra/Matrix.php:3474
```

Here is the R output:
```
> A = rbind(c(0),c(0))
> A
     [,1]
[1,]    0
[2,]    0
> qrA = qr(A)
> qr.Q(qrA)
     [,1]
[1,]    1
[2,]    0
> qr.R(qrA)
     [,1]
[1,]    0
```

Also, here are some other unit tests I was intending to add. Please add them to your pull request to verify any fixes don't break these tests.

```php
           [
                [
                    [0],
                ],
                [
                    'Q' => [
                        [1],
                    ],
                    'R' => [
                        [0],
                    ],
                ],
            ],
            [
                [
                    [1],
                ],
                [
                    'Q' => [
                        [1],
                    ],
                    'R' => [
                        [1],
                    ],
                ],
            ],
            [
                [
                    [0, 0],
                ],
                [
                    'Q' => [
                        [1],
                    ],
                    'R' => [
                        [0, 0],
                    ],
                ],
            ],
            [
                [
                    [1, 1],
                ],
                [
                    'Q' => [
                        [1],
                    ],
                    'R' => [
                        [1, 1],
                    ],
                ],
            ],
            [
                [
                    [1],
                    [1],
                ],
                [
                    'Q' => [
                        [-0.7071068],
                        [-0.7071068],
                    ],
                    'R' => [
                        [-1.414214],
                    ],
                ],
            ],
```

Thanks for continuing to work on getting QR working.

**Comment by markrogoyski** [comment]
Just checking up on this. There is still the division-by-zero edge case to handle. Anything else remaining after that?

Do you need any help to complete this?
Thanks.

**Comment by Beakerboy** [comment]
I’m working from old to new. Feel free to jump in on anything you want. Both of us have the same goal, to get new features into the library.

**Comment by Beakerboy** [comment]
This should be good now.

**Comment by Beakerboy** [comment]
Added the extra tests you proposed, and they all pass.

**Comment by markrogoyski** [comment]
Awesome. Thanks for following up with the extra edge case handling. Looks great! Let's merge for now. Because of the importance of this method, I will continue to add more unit tests. Apologies if I find any more edge cases =)

**Comment by markrogoyski** [comment]
Thanks again for working on QR decomposition!

**Comment by markrogoyski** [comment]
I have been adding additional unit tests for QR decomposition in the develop branch. Most pass. However, I found a couple cases of square matrices that do not seem to pass.

**Test Case**
```php
[
    [
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
    ],
    [
        'Q' => [
            [-0.5773503, -0.5773503, -0.5773503],
            [-0.5773503,  0.7886751, -0.2113249],
            [-0.5773503, -0.2113249,  0.7886751],
        ],
        'R' =>[
            [-1.732051, -1.732051, -1.732051],
            [0.0000,  0.0000,  0.0000],
            [0.0000,  0.0000,  0.0000],
        ]
    ]
],
```

Here is what the QR decomposition his producing:
```
A:
[1, 1, 1]
[1, 1, 1]
[1, 1, 1]

Q:
[-0.57735026918963, 0.81649658092773, 0]
[-0.57735026918963, -0.40824829046386, -0.70710678118655]
[-0.57735026918963, -0.40824829046386, 0.70710678118655]

R:
[-1.7320508075689, -1.7320508075689, -1.7320508075689]
[1.5700924586838E-16, 1.5700924586838E-16, 1.5700924586838E-16]
[0, 0, 0]
```

Compare with R:
```R

> A <- rbind(c(1,1,1), c(1,1,1), c(1,1,1))
> A
     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    1    1    1
[3,]    1    1    1
> qr <- qr(A)
> qr.Q(qr)
           [,1]       [,2]       [,3]
[1,] -0.5773503 -0.5773503 -0.5773503
[2,] -0.5773503  0.7886751 -0.2113249
[3,] -0.5773503 -0.2113249  0.7886751
> qr.R(qr)
          [,1]      [,2]      [,3]
[1,] -1.732051 -1.732051 -1.732051
[2,]  0.000000  0.000000  0.000000
[3,]  0.000000  0.000000  0.000000
```


**Next Test Case**
```php
[
    [
        [1,  0, 0,  0,  0],
        [0,  0, 1,  0,  0],
        [1, -7, 0,  4,  2],
        [0,  4, 2, -7,  1],
        [0,  2, 0,  1, -7],
    ],
    [
        'Q' => [
            [-0.7071068, -0.5246722,  0.3333983, -0.01889766, -0.3364633],
            [ 0.0000000,  0.0000000, -0.5298652,  0.63622126, -0.5607722],
            [-0.7071068,  0.5246722, -0.3333983,  0.01889766,  0.3364633],
            [ 0.0000000, -0.5996254, -0.6787037, -0.31811063,  0.2803861],
            [ 0.0000000, -0.2998127,  0.1905133,  0.70236308,  0.6168494],
        ],
        'R' => [
            [-1.414214,  4.949747,  0.000000, -2.828427, -1.414214],
            [ 0.000000, -6.670832, -1.199251,  5.996254,  2.548408],
            [ 0.000000,  0.000000, -1.887273,  3.607846, -2.679094],
            [ 0.000000,  0.000000,  0.000000,  3.004728, -5.196857],
            [ 0.000000,  0.000000,  0.000000,  0.000000, -3.364633],
        ],
    ],
],
```

Here is what the QR decomposition his producing:
```
A:
[1, 0, 0, 0, 0]
[0, 0, 1, 0, 0]
[1, -7, 0, 4, 2]
[0, 4, 2, -7, 1]
[0, 2, 0, 1, -7]

Q:
[-0.70710678118655, 0, 8.3266726846887E-17, 0.66666666666667, 0.23570226039552]
[0, 1, 0, 0, 0]
[-0.70710678118655, 0, -8.3266726846887E-17, -0.66666666666667, -0.23570226039552]
[0, 0, -1, 1.4805414026219E-17, 1.463331654135E-17]
[0, 0, 1.1102230246252E-16, -0.33333333333333, 0.94280904158206]

R:
[-1.4142135623731, 4.9497474683058, 0, -2.8284271247462, -1.4142135623731]
[0, 0, 1, 0, 0]
[0, -4, -2, 7, -1]
[0, 4, 2.9610828052438E-17, -3, 1]
[0, 3.5355339059327, 2.9266633082701E-17, 2.2204460492503E-16, -7.0710678118655]
```

Compare with R:
```R
> A <- rbind(c(1,0,0,0,0), c(0,0,1,0,0), c(1,-7,0,4,2), c(0,4,2,-7,1), c(0,2,0,1,-7))
> A
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    0    1    0    0
[3,]    1   -7    0    4    2
[4,]    0    4    2   -7    1
[5,]    0    2    0    1   -7
> qr <- qr(A)
> qr.Q(qr)
           [,1]       [,2]       [,3]        [,4]       [,5]
[1,] -0.7071068 -0.5246722  0.3333983 -0.01889766 -0.3364633
[2,]  0.0000000  0.0000000 -0.5298652  0.63622126 -0.5607722
[3,] -0.7071068  0.5246722 -0.3333983  0.01889766  0.3364633
[4,]  0.0000000 -0.5996254 -0.6787037 -0.31811063  0.2803861
[5,]  0.0000000 -0.2998127  0.1905133  0.70236308  0.6168494
> qr.R(qr)
          [,1]      [,2]      [,3]      [,4]      [,5]
[1,] -1.414214  4.949747  0.000000 -2.828427 -1.414214
[2,]  0.000000 -6.670832 -1.199251  5.996254  2.548408
[3,]  0.000000  0.000000 -1.887273  3.607846 -2.679094
[4,]  0.000000  0.000000  0.000000  3.004728 -5.196857
[5,]  0.000000  0.000000  0.000000  0.000000 -3.364633
```

**Comment by Beakerboy** [comment]
Have you checked if A=Q*R and if Q is orthogonal and R is upper triangular, because, in the end, those are the important features.

**Comment by markrogoyski** [comment]
The 5x5 matrix is not producing an R that is upper triangular.

R gets an upper triangular R matrix:
```R
> A <- rbind(c(1,0,0,0,0), c(0,0,1,0,0), c(1,-7,0,4,2), c(0,4,2,-7,1), c(0,2,0,1,-7))
> A
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    0    1    0    0
[3,]    1   -7    0    4    2
[4,]    0    4    2   -7    1
[5,]    0    2    0    1   -7

> qr.R(qr)
          [,1]      [,2]      [,3]      [,4]      [,5]
[1,] -1.414214  4.949747  0.000000 -2.828427 -1.414214
[2,]  0.000000 -6.670832 -1.199251  5.996254  2.548408
[3,]  0.000000  0.000000 -1.887273  3.607846 -2.679094
[4,]  0.000000  0.000000  0.000000  3.004728 -5.196857
[5,]  0.000000  0.000000  0.000000  0.000000 -3.364633
```

But the QR decomposition we're computing does not:
```
R:
[-1.4142135623731, 4.9497474683058, 0, -2.8284271247462, -1.4142135623731]
[0, 0, 1, 0, 0]
[0, -4, -2, 7, -1]
[0, 4, 2.9610828052438E-17, -3, 1]
[0, 3.5355339059327, 2.9266633082701E-17, 2.2204460492503E-16, -7.0710678118655]
```

The Q that is computed is orthogonal and A = QR, but R is not upper triangular it seems.

**Comment by markrogoyski** [comment]
I think I have found and fixed the issue. The sign switching part I think should only allow positive or negative switching (1 or -1), but it was using the `signum` function, which will give you 0 for the 0 case.

This line:
```php
// α is the square root of the sum of squares of x with the correct sign
$α = Special::sgn($x[0][0]) * $x->frobeniusNorm();
```

I changed it to:
```php
$sign = $x[0][0] >= 0 ? 1 : -1;
$α    = $sign * $x->frobeniusNorm();
```

And now I can get this matrix to pass with A = QR, Q being orthogonal and R being upper triangular.

I've merged this change into develop. I will do some more testing but so far it is looking good.

**Comment by Beakerboy** [comment]
That sounds right. Thanks! I had not had a chance to dive deeper into it. My opinion of decompositions is to just test the properties of the resulting matrices, and that they combine back into the original. If the implementation details change, we would not want to have to remake the tests.

**Pull request merged**
