### PR TITLE
PCA for non-standardized data.

### PR DESCRIPTION
**Pull request by Beakerboy**
* Normalizing matrix prior to calculating eigenvectors. This improves computability.
* Added test cases for non-centered and non-scaled PCA
* Fixed the two previously mentioned bugs

### CODE REVIEW

**Comment by markrogoyski** [comment]
Thanks for following up.

I merged this code into my PCA unit test branch, but I still am getting different results on the eigenvalues and Q values.

Here are my tests:
```php
    /**
     * @throws Exception\MathException
     */
    public static function setUpBeforeClass()
    {
        self::$A = SampleData::mtcars();

        // Remove top row, left column, and categorical variables
        self::$matrix = MatrixFactory::create(self::$A)->rowExclude(0)->columnExclude(9)->columnExclude(8)->columnExclude(0);
        self::$pca = new PCA(self::$matrix, false, true);
    }

    /**
     * @test The class returns the correct eigenvalues
     *
     * R code for expected values:
     * library(mdatools)
     * data = mtcars[,c(1:7,10,11)]
     * model = pca(data, center=FALSE, scale=TRUE)
     * print(model$eigenvals)
     */
    public function testEigenvalues()
    {
        // Given
        $expected = [4.030377e-01, 5.538161e+00, 2.072459e+00, 3.803137e-01, 2.326922e-01, 1.534309e-01, 1.051069e-01, 9.254194e-02, 2.225659e-02];

        // When
        $eigenvalues = self::$pca->getEigenvalues()->getVector();

        // Then
        $this->assertEquals($expected, $eigenvalues, '', .00001);
    }

    /**
     * @test The class returns the correct critical Q distances
     *
     * R code for expected values:
     * library(mdatools)
     * data = mtcars[,c(1:7,10,11)]
     * model = pca(data, center=FALSE, scale=TRUE)
     * show(model$Qlim)
     */
    public function testCriticalQ()
    {
        // Given
        $expected = [25.824597, 9.343233, 2.3843107, 1.4845012, 0.9577895, 0.6182419, 0.3849731, 0.08339018, 0];

        // When
        $criticalQ = self::$pca->getCriticalQ();

        // Then
        $this->assertEquals($expected, $criticalQ, '', .00001);
    }
```

The PHPUnit result:
```
There were 2 failures:

1) MathPHP\Tests\Statistics\Multivariate\PCACenterFalseScaleTrueTest::testEigenvalues
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 0.4030377
-    1 => 5.538161
-    2 => 2.072459
-    3 => 0.3803137
-    4 => 0.2326922
-    5 => 0.1534309
-    6 => 0.1051069
-    7 => 0.09254194
-    8 => 0.02225659
+    0 => 222.3321201138189
+    1 => 5.54094292838142
+    2 => 2.072538708724308
+    3 => 0.3804255065215178
+    4 => 0.2327154102919932
+    5 => 0.1534447103925525
+    6 => 0.10510697776259888
+    7 => 0.09255475885315632
+    8 => 0.022256619485386715
 )

2) MathPHP\Tests\Statistics\Multivariate\PCACenterFalseScaleTrueTest::testCriticalQ
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 25.824597
-    1 => 9.343233
-    2 => 2.3843107
-    3 => 1.4845012
-    4 => 0.9577895
-    5 => 0.6182419
-    6 => 0.3849731
-    7 => 0.08339018
+    0 => 25.83533506089264
+    1 => 9.34378604439335
+    2 => 2.384789575884407
+    3 => 1.4846309489027265
+    4 => 0.9578609326060092
+    5 => 0.6182775913659855
+    6 => 0.3850209178153974
+    7 => 0.08339028692397615
     8 => 0
 )
```

And the R reference data I was using for expected values:
```R
> data = mtcars[,c(1:7,10,11)]
> model = pca(data, center=FALSE, scale=TRUE)
> model$eigenvals
 [1] 4.030377e-01 5.538161e+00 2.072459e+00 3.803137e-01 2.326922e-01 1.534309e-01 1.051069e-01 9.254194e-02 2.225659e-02 1.794412e-29
[11] 5.886487e-30 1.533721e-30 9.283357e-31 7.376389e-31 2.857330e-31 1.950237e-31 1.809030e-31 1.002742e-31

> data = mtcars[,c(1:7,10,11)]
> model = pca(data, center=FALSE, scale=TRUE)
> model$Qlim
                                 Comp 1    Comp 2    Comp 3    Comp 4    Comp 5    Comp 6    Comp 7     Comp 8 Comp 9
Critical limit (alpha = 0.05) 25.824597  9.343233 2.3843107 1.4845012 0.9577895 0.6182419 0.3849731 0.08339018      0
Outliers limit (gamma = 0.01) 43.664393 16.589770 3.5409345 2.1840546 1.4225843 0.9537207 0.6674222 0.14657685      0
Mean (u0)                      8.331236  2.963448 0.9556757 0.5871385 0.3616955 0.2130459 0.1112235 0.02156110      0
DoF                            1.000000  1.000000 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 1.00000000      1
```

Am I doing something wrong in R to generate the data? Is there some other problem in the PCA calculation for center being false? Thanks.

**Comment by Beakerboy** [comment]
The eigenvalue does not make any sense to me. The first eigenvalue should be the largest, and the rsq is the ratio of the eigenvalue to he sum of all. If PC1 is 90% of the total, it cannot be .4. 200 would make more sense.
https://www.reddit.com/r/AskStatistics/comments/cwq4wc/strange_result_for_eigenvalues_on_pca_in_r/

**Comment by Beakerboy** [comment]
I made some changes after diving into the R source code. It uses the actual variance of the scores instead of the eigenvalues. When the data is centered, they are equivalent.

**Comment by markrogoyski** [comment]
Thanks for following up and investigating. It looks like these changes make all the center=false tests pass. Thanks!

**Comment by Beakerboy** [comment]
The PCA method in R used to use the (SVD->D ** 2) / (n - 1) as the eigenvalues, but changed in version 0.9.1, which was a year ago.

**Pull request merged**
